#!/usr/bin/env bash

# secret.pdf -> pdf is suffix (file extension)

file=secret.projectX.pdf

# starts from beginning go to 1st . and removes everything before. # -> non-greedy
echo "${file#*.}"
# greedy (2 hashes ##)
echo "${file##*.}"

# start from end
echo "${file%.*}"
echo "${file%%.*}"

# enviroment variable
echo "$PWD"
